version: "2"

linters:
  default: all
  disable:
    - gochecknoglobals
    - ireturn
    - wsl # Deprecated
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/darkweak/rudy
            - github.com/dustin/go-humanize
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - go.uber.org/zap
            - golang.org/x/net
            - gopkg.in/yaml.v3
issues:
  fix: true
